#!/usr/bin/env python

f = open("my_experiment_output.tr")
result_list = []

for line in f:
    result_list.append(line)

packetloss = 0
recv = 0
startTime = 0
endTime = 0
totalrecvsize = 0
for packet in result_list:
    packetEle = packet.split()
    if(packetEle[0]=="d"):
        packetloss = packetloss + 1
    if(packetEle[0]=="r"):
        recv = recv + 1
        if (startTime == 0):
            startsTime =  packetEle[1]
        endTime = float(packetEle[1])
        totalrecvsize = totalrecvsize + int(packetEle[5])
print recv
print totalrecvsize
print endTime - startTime
