#!/usr/bin/env python

f = open("experiment1.tr")
result_list = []

for line in f:
    result_list.append(line)

packetloss = 0
dequeue = 0.0
startTime = 0
endTime = 0
totalrecvsize = 0
for packet in result_list:
    packetEle = packet.split()
    if(packetEle[0]=="d"):
        packetloss = packetloss + 1
    if(packetEle[0]=="-" and packetEle[2]=="1" and packetEle[3]== "2" and packetEle[4]=="tcp"):
        dequeue = dequeue + 1
        if (startTime == 0):
            startsTime =  packetEle[1]
        endTime = float(packetEle[1])
        totalrecvsize = totalrecvsize + int(packetEle[5])
print packetloss/dequeue
print totalrecvsize
print endTime - startTime
