#!/usr/bin/env python
import sys
with open("experiment2.txt", 'r') as f:
    contents = f.read()

with open("experiment2.tcl", 'w') as tclf:
    c = contents % {'n': sys.argv[1], 'v1': sys.argv[2], 'v2': sys.argv[3]}
    tclf.write(c)
